import "./assets/style.css";
import Line from "./components/Line/Line";
// import Background from "./components/Background";
import SimpleNav from "./components/Navbar/Simplenav";
import Panel from "./components/Panels/Panel";
import PanelContent from "./components/Panels/PanelContent";
import NavButtons from "./components/Buttons/NavButtons";

function App() {
  return (
    <>
      <Line></Line>

      <div id="top-container">
        <SimpleNav></SimpleNav>

        <div id="mid-panels">
          <Panel>
            <PanelContent content="View"></PanelContent>
            <PanelContent content="Generated by"></PanelContent>
            <PanelContent content="DarkSushi Model"></PanelContent>
          </Panel>

          <Panel>
            <PanelContent content="Example data:"></PanelContent>
            <PanelContent content="here could be anything, ads some list "></PanelContent>
          </Panel>
        </div>

        <img
          src="/girl-background.png"
          alt="Image Background"
          id="background-image"
        />
      </div>

      <div id="mid-page-navbar">
        <NavButtons></NavButtons>
        <NavButtons></NavButtons>
        <NavButtons></NavButtons>
        <NavButtons></NavButtons>
        <NavButtons></NavButtons>
      </div>

      <div id="content-zone">
        <div id="left-zone"></div>
        <div id="right-zone"></div>
      </div>
    </>
  );
}

export default App;
